#!/bin/sh
set -e

rm -rf ./integration-output

npx -- @diplodoc/cli@latest -i ./integration -o ./integration-output --single-page

if [[ ! -d "node_modules" ]]; then
    npm ci
fi

if [[ ! -d "build" ]]; then
    npm run build
fi

node ./build/cmd/index.js --input ./integration-output