on:
  push:
    branches: [master]

name: release

permissions:
  contents: write
  pull-requests: write
  id-token: write  # Обязательно для OIDC/Trusted Publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - uses: codex-team/action-nodejs-package-info@v1
        id: package
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.YC_UI_BOT_GITHUB_TOKEN}}
          release-type: node
      - run: |
          npm config delete //registry.npmjs.org/:_authToken
          npm publish --provenance --access public
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
